trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.5
    architecture: 'x64'

- script: |
    pip install pyang
  displayName: 'Install prerequisites'

- script: |
    pyang -f tree org-openroadm-alarm.yang
  displayName: 'go to Common'
  workingDirectory: $(Build.SourcesDirectory)/model/Common
