trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.5
    architecture: 'x64'

- script: |
    pip install pyang
  displayName: 'Install prerequisites'

- script: |
    pyang *.yang
  displayName: 'check common'
  workingDirectory: $(Build.SourcesDirectory)/model/Common

- script: |
    pyang *.yang
  displayName: 'check Device'
  workingDirectory: $(Build.SourcesDirectory)/model/Device

- script: |
    pyang *.yang
  displayName: 'Check Network'
  workingDirectory: $(Build.SourcesDirectory)/model/Network

- script: |
    pyang *.yang
  displayName: 'Check Service'
  workingDirectory: $(Build.SourcesDirectory)/model/Service